# Ansible playbook for installing java
---
- name: Install Java openJDK
  hosts: "masters, slaves, prods"
  become: yes
  roles:
    - jdk

- name: Install maven
  hosts: "masters, slaves"
  become: yes
  roles:
    - maven

- name: Install git
  hosts: masters
  become: yes
  roles:
    - git

- name: Install docker.io
  hosts: "masters, slaves, prods"
  become: yes
  roles:
    - docker

- name: Install pass for docker login
  hosts: masters
  become: yes
  apt:
    name: pass
    state: present
    update_cache: yes
