# Ansible playbook for installing java
---
- name: Install Java openJDK
  hosts: "tag_Name_master, tag_Name_slave, tag_Name_prod"
  become: yes
  roles:
    - jdk

- name: Install maven
  hosts: "tag_Name_master, tag_Name_slave"
  become: yes
  roles:
    - maven

- name: Install git
  hosts: tag_Name_master
  become: yes
  roles:
    - git

- name: Install docker.io
  hosts: "tag_Name_master, tag_Name_slave, tag_Name_prod"
  become: yes
  roles:
    - docker
