- name: Install latest openJDK 8 JDK
  apt:
    name: openjdk-8-jdk
    update_cache: yes
    state: present

- name: Check java version
  shell: "java -version"
  register: jdk_version

- name: Display java version
  debug:
    var: jdk_version