- name: Install unzip
  apt:
    name: unzip
    update_cache: yes
    state: present

- name: Install latest maven
  get_url:
    url: "https://dlcdn.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.zip"
    dest: "/home/{{ user_name }}"
    mode: 0755

- name: Extract maven zip
  unarchive:
    src: "/home/{{ user_name }}/apache-maven-{{ maven_version }}-bin.zip"
    dest: "/home/{{ user_name }}"
    remote_src: yes